<?php

namespace Mayssoun\MagazineBundle\Repository;

/**
 * BloggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloggerRepository extends \Doctrine\ORM\EntityRepository
{
}
